name: vania_sample
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.4

dependency_overrides:
  pointycastle: 3.7.3